# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='result',
        ),
        migrations.AddField(
            model_name='job',
            name='result_id',
            field=models.CharField(editable=False, max_length=36, null=True),
        ),
    ]
