sudo: required

services:
  - docker

language: python
python:
  - "2.7"

env:
  - TARGET_ENV=dev
  - TARGET_ENV=test

install:
  - docker -v
  - docker-compose -v
  - bin/mk${TARGET_ENV}env.sh
  - bin/deploy.sh

script: true
