version: '2'
services:
  web:
    image: hippo_web
    hostname: web
    ports:
      - "80:80"
    volumes:
      - .:/hippo
    environment:
      MQ_HOST: mq
      MQ_USER: hippo
      MQ_PASS: slow
      DB_HOST: db
      DB_DB: hippo
      DB_USER: hippo
      DB_PASS: slow
      RDB_HOST: rdb
      RDB_DB: 0
      RDB_PASS: slow
      CONN_MAX_AGE: 1800
      BROKER_HEARTBEAT: 60
      BROKER_POOL_LIMIT: 10
      CELERY_REDIS_MAX_CONNECTIONS: 10
      WORKERS: 4
      MAX_REQUESTS: 1000
    command: ./web.sh
    logging:
      options:
        max-size: 5m
        max-file: '5'
    restart: always
  worker:
    image: hippo_worker
    hostname: worker
    volumes:
      - .:/hippo
    environment:
      MQ_HOST: mq
      MQ_USER: hippo
      MQ_PASS: slow
      RDB_HOST: rdb
      RDB_DB: 0
      RDB_PASS: slow
      CELERYD_MAX_TASKS_PER_CHILD: 1000
      CONCURRENCY: 2
    command: ./worker.sh
    logging:
      options:
        max-size: 5m
        max-file: '5'
    restart: always
  mq:
    image: rabbitmq:3.6
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: hippo
      RABBITMQ_DEFAULT_PASS: slow
    logging:
      options:
        max-size: 5m
        max-file: '5'
    restart: always
  db:
    image: postgres:9.5
    hostname: db
    environment:
      POSTGRES_USER: hippo
      POSTGRES_PASSWORD: slow
    command: postgres -c max_connections=100 -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=3
    logging:
      options:
        max-size: 5m
        max-file: '5'
    restart: always
  rdb:
    image: redis:3.0
    hostname: rdb
    command: redis-server --requirepass slow --maxclients 10000 --tcp-keepalive 30
    logging:
      options:
        max-size: 5m
        max-file: '5'
    restart: always
