version: '2'
services:
  web:
    extends:
      file: docker-compose.django.yml
      service: django
    image: hippo_web
    hostname: web
    environment:
      WORKERS: 2
      MAX_REQUESTS: 1000
      ADMIN_USER: admin
      ADMIN_PASS: admin
    command: ./web.sh
  worker:
    extends:
      file: docker-compose.django.yml
      service: django
    image: hippo_worker
    hostname: worker
    environment:
      CONCURRENCY: 4
      MAX_TASKS_PER_CHILD: 1000
    command: ./worker.sh
  db:
    extends:
      file: docker-compose.base.yml
      service: base
    image: postgres:9.5
    hostname: db
    environment:
      POSTGRES_USER: hippo
      POSTGRES_PASSWORD: slow
    command: postgres -c max_connections=100 -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=3
  rdb:
    extends:
      file: docker-compose.base.yml
      service: base
    image: redis:3.0
    hostname: rdb
    command: redis-server --requirepass slow --maxclients 10000 --tcp-keepalive 30
  mdb:
    extends:
      file: docker-compose.base.yml
      service: base
    image: mongo:3.2
    hostname: mdb
    environment:
      ADMIN_USER: hippo
      ADMIN_PASS: slow
    command: mongod --auth --maxConns 1000
  mq:
    extends:
      file: docker-compose.base.yml
      service: base
    image: rabbitmq:3.6
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: hippo
      RABBITMQ_DEFAULT_PASS: slow
  proxy:
    extends:
      file: docker-compose.base.yml
      service: base
    depends_on:
      - web
    image: hippo_proxy
    hostname: proxy
    environment:
      WEB_HOST: web
    command: ./proxy.sh
