version: '2'
services:
  web:
    image: hippo_web
    hostname: web
    ports:
      - "80:80"
    volumes:
      - .:/hippo
    environment:
      MQ_HOST: mq
      MQ_USER: hippo
      MQ_PASS: slow
      DB_HOST: db
      DB_DB: hippo
      DB_USER: hippo
      DB_PASS: slow
      RDB_HOST: rdb
      RDB_DB: 0
      RDB_PASS: slow
    command: ./web.sh
    restart: unless-stopped
  worker:
    image: hippo_worker
    hostname: worker
    volumes:
      - .:/hippo
    environment:
      MQ_HOST: mq
      MQ_USER: hippo
      MQ_PASS: slow
      RDB_HOST: rdb
      RDB_DB: 0
      RDB_PASS: slow
    command: ./worker.sh
    restart: unless-stopped
  mq:
    image: rabbitmq:3.6
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: hippo
      RABBITMQ_DEFAULT_PASS: slow
    restart: unless-stopped
  db:
    image: postgres:9.5
    hostname: db
    environment:
      POSTGRES_USER: hippo
      POSTGRES_PASSWORD: slow
    command: postgres -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=3
    restart: unless-stopped
  rdb:
    image: redis:3.0
    hostname: rdb
    command: redis-server --requirepass slow --tcp-keepalive 30
    restart: unless-stopped
