version: '2'
services:
  web:
    extends:
      file: docker-compose.base.yml
      service: base
    image: hippo_web
    hostname: web
    environment:
      WORKERS: 4
      MAX_REQUESTS: 1000
      ALLOWED_HOSTS: 'www.hippo.com, hippo.com'
      MQ_HOST: mq
      MQ_USER: hippo
      MQ_PASS: slow
      DB_HOST: db
      DB_DB: hippo
      DB_USER: hippo
      DB_PASS: slow
      RDB_HOST: rdb
      RDB_DB: 0
      RDB_PASS: slow
      CONN_MAX_AGE: 1800
      BROKER_HEARTBEAT: 60
      BROKER_POOL_LIMIT: 10
      CELERY_REDIS_MAX_CONNECTIONS: 10
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 1
      EMAIL_USER: vsemionov.hippo@gmail.com
      EMAIL_PASS: hipposlow
      ADMIN_NAME: 'Hippo Admin'
      ADMIN_EMAIL: vsemionov.hippo@gmail.com
    command: ./web.sh
  proxy:
    extends:
      file: docker-compose.base.yml
      service: base
    depends_on:
      - web
    image: hippo_proxy
    hostname: proxy
    environment:
      WORKER_CONNECTIONS: 1024
      WEB_HOST: web
    command: ./proxy.sh
  worker:
    extends:
      file: docker-compose.base.yml
      service: base
    image: hippo_worker
    hostname: worker
    environment:
      CONCURRENCY: 8
      CELERYD_MAX_TASKS_PER_CHILD: 1000
      MQ_HOST: mq
      MQ_USER: hippo
      MQ_PASS: slow
      DB_HOST: db
      DB_DB: hippo
      DB_USER: hippo
      DB_PASS: slow
      RDB_HOST: rdb
      RDB_DB: 0
      RDB_PASS: slow
      CONN_MAX_AGE: 1800
      BROKER_HEARTBEAT: 60
      BROKER_POOL_LIMIT: 10
      CELERY_REDIS_MAX_CONNECTIONS: 10
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 1
      EMAIL_USER: vsemionov.hippo@gmail.com
      EMAIL_PASS: hipposlow
      ADMIN_NAME: 'Hippo Admin'
      ADMIN_EMAIL: vsemionov.hippo@gmail.com
      LOCAL_SETTINGS_FILE: /hippo/hippo/hippo/worker.conf
    command: ./worker.sh
  mq:
    extends:
      file: docker-compose.base.yml
      service: base
    image: rabbitmq:3.6
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: hippo
      RABBITMQ_DEFAULT_PASS: slow
  db:
    extends:
      file: docker-compose.base.yml
      service: base
    image: postgres:9.5
    hostname: db
    environment:
      POSTGRES_USER: hippo
      POSTGRES_PASSWORD: slow
    command: postgres -c max_connections=100 -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=3
  rdb:
    extends:
      file: docker-compose.base.yml
      service: base
    image: redis:3.0
    hostname: rdb
    command: redis-server --requirepass slow --maxclients 10000 --tcp-keepalive 30
