version: '2'
services:
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - .:/hippo
    restart: 'no'
  worker:
    build: .
    volumes:
      - .:/hippo
    restart: 'no'
  mq:
    ports:
      - '5672:5672'
    restart: 'no'
  db:
    ports:
      - '5432:5432'
    restart: 'no'
  rdb:
    ports:
      - '6379:6379'
    restart: 'no'
