version: '2'
services:
  web:
    ports:
      - '8000:8000'
    volumes:
      - .:/hippo
    environment:
      LOCAL_SETTINGS_FILE: /hippo/hippo/hippo/dev.conf
    command: python manage.py runserver 0.0.0.0:8000
    restart: 'no'
  worker:
    volumes:
      - .:/hippo
    restart: 'no'
  proxy:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/hippo
    restart: 'no'
  db:
    ports:
      - '5432:5432'
    restart: 'no'
  rdb:
    ports:
      - '6379:6379'
    restart: 'no'
  mdb:
    ports:
      - '27017:27017'
    restart: 'no'
  mq:
    ports:
      - '5672:5672'
    restart: 'no'
